// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const imageNotFoundPng = 'assets/images/image_not_found.png';
  static const imgArrowLeftSvg = 'assets/images/img_arrow_left.svg';
  static const imgBallPng = 'assets/images/img_ball.png';
  static const imgBallSvg = 'assets/images/img_ball.svg';
  static const imgBallsSvg = 'assets/images/img_balls.svg';
  static const imgBlueStarsPng = 'assets/images/img_blue_stars.png';
  static const imgBlueStars_13x13Png = 'assets/images/img_blue_stars_13x13.png';
  static const imgBlueStars_1Png = 'assets/images/img_blue_stars_1.png';
  static const imgBlueStars_21x21Png = 'assets/images/img_blue_stars_21x21.png';
  static const imgBlueStars_24x19Png = 'assets/images/img_blue_stars_24x19.png';
  static const imgCalendarSvg = 'assets/images/img_calendar.svg';
  static const imgEllipse_1Png = 'assets/images/img_ellipse_1.png';
  static const imgEllipse_2Png = 'assets/images/img_ellipse_2.png';
  static const imgEllipse_4Png = 'assets/images/img_ellipse_4.png';
  static const imgEmptyPng = 'assets/images/img_empty.png';
  static const imgFacebookSvg = 'assets/images/img_facebook.svg';
  static const imgGlobe_1Png = 'assets/images/img_globe_1.png';
  static const imgGraphicsPng = 'assets/images/img_graphics.png';
  static const imgGroup_28Svg = 'assets/images/img_group_28.svg';
  static const imgGroup_2Png = 'assets/images/img_group_2.png';
  static const imgGroup_3Svg = 'assets/images/img_group_3.svg';
  static const imgGroup_4Svg = 'assets/images/img_group_4.svg';
  static const imgGroup_5Svg = 'assets/images/img_group_5.svg';
  static const imgGroup_7208Png = 'assets/images/img_group_7208.png';
  static const imgHand_1Png = 'assets/images/img_hand_1.png';
  static const imgLockSvg = 'assets/images/img_lock.svg';
  static const imgMegaphoneSvg = 'assets/images/img_megaphone.svg';
  static const imgNavChatSvg = 'assets/images/img_nav_chat.svg';
  static const imgNavDiscoverSvg = 'assets/images/img_nav_discover.svg';
  static const imgNavStatisticsSvg = 'assets/images/img_nav_statistics.svg';
  static const imgOyuPng = 'assets/images/img_oyu.png';
  static const imgProfilePictureWebp = 'assets/images/img_profilePicture.webp';
  static const imgRectangle_556Png = 'assets/images/img_rectangle_556.png';
  static const imgRobotPng = 'assets/images/img_robot.png';
  static const imgTengri_1TracedSvg = 'assets/images/img_tengri_1_traced.svg';
  static const imgUploadSvg = 'assets/images/img_upload.svg';
  static const imgUserSvg = 'assets/images/img_user.svg';
  static const imgVuesaxOutlineArrowLeftPng = 'assets/images/img_vuesax_outline_arrow_left.png';
  static const imgVuesaxOutlineArrowLeftSvg = 'assets/images/img_vuesax_outline_arrow_left.svg';
  static const imgZhibekPng = 'assets/images/img_zhibek.png';
  static const img_6179551_1TracedPng = 'assets/images/img_6179551_1_traced.png';
  static const img_6179551_1TracedRed_400Png = 'assets/images/img_6179551_1_traced_red_400.png';
  static const img_6179551_1TracedSvg = 'assets/images/img_6179551_1_traced.svg';
}

class AssetsSvgs {

}

